export const GET_WORKWITHUSES = 'GET_WORKWITHUSES';
export const GET_WORKWITHUSES_BY_CATEGORIES = 'GET_WORKWITHUSES_BY_CATEGORIES';
export const GET_WORKWITHUSES_SHOW = 'GET_WORKWITHUSES_SHOW';

//Employments
export const GET_CATEGORYEMPLOYMENTS = 'GET_CATEGORYEMPLOYMENTS';
export const GET_CATEGORYEMPLOYMENTS_BY_CITY = 'GET_CATEGORYEMPLOYMENTS_BY_CITY';
export const GET_CATEGORYEMPLOYMENTS_BY_USER = 'GET_CATEGORYEMPLOYMENTS_BY_USER';
export const UNACTIVE_ANNONCE_EMPLOYMENT = 'UNACTIVE_ANNONCE_EMPLOYMENT';
export const ACTIVE_ANNONCE_EMPLOYMENT = 'ACTIVE_ANNONCE_EMPLOYMENT';
export const GET_EMPLOYEMENT_INTERESSE = 'GET_EMPLOYEMENT_INTERESSE';
export const GET_EMPLOYEMENT_SHOW_USER_SITE = 'GET_EMPLOYEMENT_SHOW_USER_SITE';
export const FAVORITE_EMPLOYEMENT_SHOW_ADD = 'FAVORITE_EMPLOYEMENT_SHOW_ADD';
export const FAVORITE_EMPLOYEMENT_SHOW_REMOVE = 'FAVORITE_EMPLOYEMENT_SHOW_REMOVE';
export const FAVORITE_EMPLOYEMENT_ADD = 'FAVORITE_EMPLOYEMENT_ADD';
export const FAVORITE_EMPLOYEMENT_REMOVE = 'FAVORITE_EMPLOYEMENT_REMOVE';
export const UNACTIVE_EMPLOYEMENT = 'UNACTIVE_EMPLOYEMENT';
export const DELETE_EMPLOYEMENT = 'DELETE_EMPLOYEMENT';

export const STATUS_COMMENT_EMPLOYMENT_ADD = 'STATUS_COMMENT_EMPLOYMENT_ADD';
export const STATUS_COMMENT_EMPLOYMENT_REMOVE = 'STATUS_COMMENT_EMPLOYMENT_REMOVE';
export const LIKE_EMPLOYEMENT_ADD = 'LIKE_EMPLOYEMENT_ADD';
export const LIKE_EMPLOYEMENT_REMOVE = 'LIKE_EMPLOYEMENT_REMOVE';

//FORUM

export const GET_FORUM_SHOW_USER_SITE = 'GET_FORUM_SHOW_USER_SITE';
export const FAVORITE_FORUM_SHOW_ADD = 'FAVORITE_FORUM_SHOW_ADD';
export const FAVORITE_FORUM_SHOW_REMOVE = 'FAVORITE_FORUM_SHOW_REMOVE';
export const LIKE_FORUM_ADD = 'LIKE_FORUM_ADD';
export const LIKE_FORUM_REMOVE = 'LIKE_FORUM_REMOVE';



//Contactservices
export const GET_RED_CONTACTSERVICEMPLOYMENT_SHOW = 'GET_RED_CONTACTSERVICEMPLOYMENT_SHOW';
export const GET_RED_CONTACTSERVICEMPLOYMENT = 'GET_RED_CONTACTSERVICEMPLOYMENT';
export const FAVORITE_CONTACTSERVICE_ADD = 'FAVORITE_CONTACTSERVICE_ADD';
export const FAVORITE_CONTACTSERVICE_REMOVE = 'FAVORITE_CONTACTSERVICE_REMOVE';
export const ARCHVEMENT_CONTACTSERVICE_ADD = 'ARCHVEMENT_CONTACTSERVICE_ADD';
export const ARCHVEMENT_CONTACTSERVICE_REMOVE = 'ARCHVEMENT_CONTACTSERVICE_REMOVE';
export const ACTIVE_CONTACTSERVICE_ADD = 'ACTIVE_CONTACTSERVICE_ADD';
export const ACTIVE_CONTACTSERVICE_REMOVE = 'ACTIVE_CONTACTSERVICE_REMOVE';


