export const GET_WORKWITHUSES = 'GET_WORKWITHUSES';
export const GET_WORKWITHUSES_BY_CATEGORIES = 'GET_WORKWITHUSES_BY_CATEGORIES';
export const GET_WORKWITHUSES_SHOW = 'GET_WORKWITHUSES_SHOW';
//export const NEW_POST = 'NEW_POST';
