export const GET_WORKWITHUSES = 'GET_WORKWITHUSES';
export const GET_WORKWITHUSES_BY_CATEGORIES = 'GET_WORKWITHUSES_BY_CATEGORIES';
export const GET_WORKWITHUSES_SHOW = 'GET_WORKWITHUSES_SHOW';

//Employments
export const GET_CATEGORYEMPLOYMENTS = 'GET_CATEGORYEMPLOYMENTS';
export const GET_CATEGORYEMPLOYMENTS_BY_CATEGORY = 'GET_CATEGORYEMPLOYMENTS_BY_CATEGORY';
export const GET_CATEGORYEMPLOYMENTS_BY_USER = 'GET_CATEGORYEMPLOYMENTS_BY_USER';
export const UNACTIVE_ANNONCE_EMPLOYMENT = 'UNACTIVE_ANNONCE_EMPLOYMENT';
export const ACTIVE_ANNONCE_EMPLOYMENT = 'ACTIVE_ANNONCE_EMPLOYMENT';
export const GET_EMPLOYEMENT_INTERESSE = 'GET_EMPLOYEMENT_INTERESSE';
export const GET_EMPLOYEMENT_SHOW_USER_SITE = 'GET_EMPLOYEMENT_SHOW_USER_SITE';
export const FAVORITE_EMPLOYEMENT_SHOW_ADD = 'FAVORITE_EMPLOYEMENT_SHOW_ADD';
export const FAVORITE_EMPLOYEMENT_SHOW_REMOVE = 'FAVORITE_EMPLOYEMENT_SHOW_REMOVE';
export const FAVORITE_EMPLOYEMENT_ADD = 'FAVORITE_EMPLOYEMENT_ADD';
export const FAVORITE_EMPLOYEMENT_REMOVE = 'FAVORITE_EMPLOYEMENT_REMOVE';
export const UNACTIVE_EMPLOYEMENT = 'UNACTIVE_EMPLOYEMENT';
export const DELETE_EMPLOYEMENT = 'DELETE_EMPLOYEMENT';
export const STATUS_COMMENT_EMPLOYMENT_ADD = 'STATUS_COMMENT_EMPLOYMENT_ADD';
export const STATUS_COMMENT_EMPLOYMENT_REMOVE = 'STATUS_COMMENT_EMPLOYMENT_REMOVE';
export const LIKE_EMPLOYEMENT_ADD = 'LIKE_EMPLOYEMENT_ADD';
export const LIKE_EMPLOYEMENT_REMOVE = 'LIKE_EMPLOYEMENT_REMOVE';

//Forum
export const GET_CATEGORYFORUMS = 'GET_CATEGORYFORUMS';
export const GET_CATEGORYFORUMS_BY_USER = 'GET_CATEGORYFORUMS_BY_USER';
export const GET_FORUM_SHOW_USER_SITE = 'GET_FORUM_SHOW_USER_SITE';
export const FAVORITE_FORUM_SHOW_ADD = 'FAVORITE_FORUM_SHOW_ADD';
export const FAVORITE_FORUM_SHOW_REMOVE = 'FAVORITE_FORUM_SHOW_REMOVE';
export const LIKE_FORUM_ADD = 'LIKE_FORUM_ADD';
export const LIKE_FORUM_REMOVE = 'LIKE_FORUM_REMOVE';

//Annonce vente
export const GET_CATEGORYANNONCEVENTES = 'GET_CATEGORYANNONCEVENTES';
export const GET_CITYANNONCEVENTES = 'GET_CITYANNONCEVENTES';
export const GET_CATEGORYANNONCEVENTES_BY_CITY = 'GET_CATEGORYANNONCEVENTES_BY_CITY';

//Annonce location
export const GET_CATEGORYANNONCELOCATIONS = 'GET_CATEGORYANNONCELOCATIONS';
export const GET_CITYANNONCELOCATIONS = 'GET_CITYANNONCELOCATIONS';
export const GET_ANNONCELOCATION_INTERESSE_BY_CATEGORY = 'GET_ANNONCELOCATION_INTERESSE_BY_CATEGORY';
export const GET_ANNONCELOCATION_INTERESSE_BY_CITY = 'GET_ANNONCELOCATION_INTERESSE_BY_CITY';
export const GET_ANNONCELOCATION_SHOW_USER_SITE = 'GET_ANNONCELOCATION_SHOW_USER_SITE';
export const STATUS_COMMENT_ANNONCELOCATION_ADD = 'STATUS_COMMENT_ANNONCELOCATION_ADD';
export const STATUS_COMMENT_ANNONCELOCATION_REMOVE = 'STATUS_COMMENT_ANNONCELOCATION_REMOVE';
export const FAVORITE_ANNONCELOCATION_SHOW_ADD = 'FAVORITE_ANNONCELOCATION_SHOW_ADD';
export const FAVORITE_ANNONCELOCATION_SHOW_REMOVE = 'FAVORITE_ANNONCELOCATION_SHOW_REMOVE';
export const FAVORITE_ANNONCELOCATION_ADD = 'FAVORITE_ANNONCELOCATION_ADD';
export const FAVORITE_ANNONCELOCATION_REMOVE = 'FAVORITE_ANNONCELOCATION_REMOVE';
export const LIKE_ANNONCELOCATION_ADD = 'LIKE_ANNONCELOCATION_ADD';
export const LIKE_ANNONCELOCATION_REMOVE = 'LIKE_ANNONCELOCATION_REMOVE';

//Blog annonce location
export const GET_BLOGANNONCELOCATION_INTERESSE = 'GET_BLOGANNONCELOCATION_INTERESSE';
export const GET_BLOGANNONCELOCATION_SHOW = 'GET_BLOGANNONCELOCATION_SHOW';
export const FAVORITE_BLOGANNONCELOCATION_ADD = 'FAVORITE_BLOGANNONCELOCATION_ADD';
export const FAVORITE_BLOGANNONCELOCATION_REMOVE = 'FAVORITE_BLOGANNONCELOCATION_REMOVE';
export const FAVORITE_BLOGANNONCELOCATION_SHOW_ADD = 'FAVORITE_BLOGANNONCELOCATION_SHOW_ADD';
export const FAVORITE_BLOGANNONCELOCATION_SHOW_REMOVE = 'FAVORITE_BLOGANNONCELOCATION_SHOW_REMOVE';
export const LIKE_BLOGANNONCELOCATION_SHOW_ADD = 'LIKE_BLOGANNONCELOCATION_SHOW_ADD';
export const LIKE_BLOGANNONCELOCATION_SHOW_REMOVE = 'LIKE_BLOGANNONCELOCATION_SHOW_REMOVE';
export const LIKE_BLOGANNONCELOCATION_ADD = 'LIKE_BLOGANNONCELOCATION_ADD';
export const LIKE_BLOGANNONCELOCATION_REMOVE = 'LIKE_BLOGANNONCELOCATION_REMOVE';
export const DELETE_BLOGANNONCELOCATION = 'DELETE_BLOGANNONCELOCATION';

//Comments
export const GET_COMMENTS_ANNONCESLOCATIONS = 'GET_COMMENTS_ANNONCESLOCATIONS';
export const GET_COMMENTS_ANNONCESRESERVATIONS = 'GET_COMMENTS_ANNONCESRESERVATIONS';
export const GET_COMMENTS_ANNONCESVENTES = 'GET_COMMENTS_ANNONCESVENTES';
export const GET_COMMENTS_BLOGANNONCERESERVATIONS = 'GET_COMMENTS_BLOGANNONCERESERVATIONS';
export const GET_COMMENTS_BLOGANNONCEVENTES = 'GET_COMMENTS_BLOGANNONCEVENTES';
export const GET_COMMENTS_EMPLOYMENTS = 'GET_COMMENTS_EMPLOYMENTS';
export const GET_COMMENTS_FORUMS = 'GET_COMMENTS_FORUMS';
export const LIKE_COMMENT_ADD = 'LIKE_COMMENT_ADD';
export const UNACTIVE_COMMENTS = 'UNACTIVE_COMMENTS';
export const DELETE_COMMENTS = 'DELETE_COMMENTS';

//Contactservices
export const GET_RED_CONTACTSERVICEMPLOYMENT_SHOW = 'GET_RED_CONTACTSERVICEMPLOYMENT_SHOW';
export const GET_RED_CONTACTSERVICEMPLOYMENT = 'GET_RED_CONTACTSERVICEMPLOYMENT';
export const FAVORITE_CONTACTSERVICE_ADD = 'FAVORITE_CONTACTSERVICE_ADD';
export const FAVORITE_CONTACTSERVICE_REMOVE = 'FAVORITE_CONTACTSERVICE_REMOVE';
export const ARCHVEMENT_CONTACTSERVICE_ADD = 'ARCHVEMENT_CONTACTSERVICE_ADD';
export const ARCHVEMENT_CONTACTSERVICE_REMOVE = 'ARCHVEMENT_CONTACTSERVICE_REMOVE';
export const ACTIVE_CONTACTSERVICE_ADD = 'ACTIVE_CONTACTSERVICE_ADD';
export const ACTIVE_CONTACTSERVICE_REMOVE = 'ACTIVE_CONTACTSERVICE_REMOVE';
export const DELETE_CONTACTSERVICE = 'DELETE_CONTACTSERVICE';


